/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Native */

#ifndef _Included_Native
#define _Included_Native
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Native
 * Method:    hello
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_Native_hello
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
