/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Native */

#ifndef CORE
#define CORE
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     core_src_jni_Core
 * Method:    hello
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_core_src_jni_Core_hello
  (JNIEnv *, jclass);


#ifdef __cplusplus
}
#endif
#endif
