name: CMake Setup

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
        distribution: 'adopt'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y imagemagick libonnxruntime-dev libraw-dev

    - name: Set library paths
      run: echo "LD_LIBRARY_PATH=/home/runner/work/A-Shot/A-Shot/core/imagemagick/lib:/home/runner/work/A-Shot/A-Shot/core/onnxruntime/lib:/usr/local/lib" >> $GITHUB_ENV

    - name: Configure and build project
      run: |
        cd /home/runner/work/A-Shot/A-Shot/core
        mkdir cmake-build-debug
        cd cmake-build-debug
        export LD_LIBRARY_PATH=/home/runner/work/A-Shot/A-Shot/core/imagemagick/lib:/home/runner/work/A-Shot/A-Shot/core/onnxruntime/lib:/usr/local/lib:$LD_LIBRARY_PATH
        cmake -S /home/runner/work/A-Shot/A-Shot/core -DBLUR_MODEL_PATH=/home/runner/work/A-Shot/A-Shot/core/checkpoints/D-DFFNet.ort \
              -DJAVA_ROOT=/opt/hostedtoolcache/Java_Adopt_jdk/11.0.23-9/x64 \
              -DCMAKE_PREFIX_PATH=/usr/local/lib/cmake/LibRaw
        cmake --build .
        cp ../imagemagick/lib/* .
        cp ../onnxruntime/lib/* .
      env:
        JAVA_HOME: /opt/hostedtoolcache/Java_Adopt_jdk/11.0.23-9/x64
        JAVA_HOME_11_X64: /opt/hostedtoolcache/Java_Adopt_jdk/11.0.23-9/x64
        LD_LIBRARY_PATH: /home/runner/work/A-Shot/A-Shot/core/imagemagick/lib:/home/runner/work/A-Shot/A-Shot/core/onnxruntime/lib:/usr/local/lib
